version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

# To spin up a docker container run ...
# $ docker-compose build && docker-compose up
# In a seperate terminal, create the database with $ docker-compose run web rake:db{create, migrate, seed}
